In [2]:
import numpy as np

In [63]:
a=[1,2,3]
b=np.array(a)
c=np.array(a*3)
print(type(a),a)
print(type(b),b)
print(type(c),c)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'> [1 2 3]
<class 'numpy.ndarray'> [1 2 3 1 2 3 1 2 3]


In [64]:
b=np.ones(3,dtype=int)
print(b)

[1 1 1]


In [65]:
b=np.zeros(4,dtype=float)
print(b)

[0. 0. 0. 0.]


In [66]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [67]:
b=np.full((3,3),5,dtype=float)
print(b)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [68]:
b=np.full(10,0,dtype=int)
b[4]=1
print(b)

[0 0 0 0 1 0 0 0 0 0]


In [69]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [70]:
np.empty(4,dtype=int)

array([5, 0, 4, 0])

In [71]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
b=np.array((3,3))
print(b)

[3 3]


In [73]:
np.arange(2,30,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [74]:
np.linspace(3,45)

array([ 3.        ,  3.85714286,  4.71428571,  5.57142857,  6.42857143,
        7.28571429,  8.14285714,  9.        ,  9.85714286, 10.71428571,
       11.57142857, 12.42857143, 13.28571429, 14.14285714, 15.        ,
       15.85714286, 16.71428571, 17.57142857, 18.42857143, 19.28571429,
       20.14285714, 21.        , 21.85714286, 22.71428571, 23.57142857,
       24.42857143, 25.28571429, 26.14285714, 27.        , 27.85714286,
       28.71428571, 29.57142857, 30.42857143, 31.28571429, 32.14285714,
       33.        , 33.85714286, 34.71428571, 35.57142857, 36.42857143,
       37.28571429, 38.14285714, 39.        , 39.85714286, 40.71428571,
       41.57142857, 42.42857143, 43.28571429, 44.14285714, 45.        ])

In [75]:
np.linspace(3,45,20)

array([ 3.        ,  5.21052632,  7.42105263,  9.63157895, 11.84210526,
       14.05263158, 16.26315789, 18.47368421, 20.68421053, 22.89473684,
       25.10526316, 27.31578947, 29.52631579, 31.73684211, 33.94736842,
       36.15789474, 38.36842105, 40.57894737, 42.78947368, 45.        ])

In [76]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [78]:
np.random.rand(10)

array([0.37134957, 0.15710141, 0.41896859, 0.48190115, 0.42093282,
       0.98993109, 0.81406051, 0.89737972, 0.11877298, 0.1928206 ])

In [79]:
b=np.random.randint(4,10)

In [80]:
np.random.randint(10,size=(4,4))

array([[6, 2, 7, 8],
       [2, 7, 3, 9],
       [1, 7, 5, 2],
       [1, 6, 3, 5]])

In [81]:
np.arange(9,50)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [82]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [83]:
np.linspace(1,5,10).round(2)

array([1.  , 1.44, 1.89, 2.33, 2.78, 3.22, 3.67, 4.11, 4.56, 5.  ])

In [84]:
b=np.random.randint(10,size=(5,4))

In [85]:
print(b)

[[7 0 1 0]
 [8 5 2 6]
 [8 8 4 0]
 [5 9 0 3]
 [0 1 0 1]]


In [86]:
b[0:4,3]

array([0, 6, 0, 3])

In [87]:
b[2:,1:3]

array([[8, 4],
       [9, 0],
       [1, 0]])

In [94]:
b=np.arange(1,21).reshape((4,5))
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [89]:
b[2][0:3]

array([11, 12, 13])

In [59]:
b[1:,3]

array([ 9, 14, 19])

In [60]:
b[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [90]:
b[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [91]:
b=np.array([1,2,0,0,4,0])
np.where(b==0)

(array([2, 3, 5], dtype=int64),)

In [98]:
b=np.arange(1,20,step=2)
print(b)
print('index of b%3==0',np.where(b%3==0))

[ 1  3  5  7  9 11 13 15 17 19]
index of b%3==0 (array([1, 4, 7], dtype=int64),)


In [100]:
b=np.arange(1,11)
print(b)
b[np.where(b%2!=0)]-=1
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  2  4  4  6  6  8  8 10]


In [138]:
b=np.arange(11,20)
b[np.where(b%2==0)]=range(2,9,2)

In [139]:
print(b)

[11  2 13  4 15  6 17  8 19]


In [140]:
b[b.argmax()]=0
print(b)

[11  2 13  4 15  6 17  8  0]


In [3]:
b=np.arange(1,11)
b[np.where(np.logical_and(3<b,b<8))]*=-1
print(b)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


In [148]:
a=np.array(("Mihir","Nikhil","Deepak","Khushal"))
b=np.array((150,170,160,168))
print(a[np.where(b>155)])

['Nikhil' 'Deepak' 'Khushal']


In [169]:
b=np.arange(21,1,-1).reshape(4,5)
print(b)
print(b[:,0].argsort())
b = b[b[:,0].argsort()]
print(b)


[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]
[3 2 1 0]
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
